# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Tongass"
license = "MIT"
licenselink = "https://github.com/redpanda1234/tongass/blob/master/LICENSE.md"
description = ""
homepage = "http://demystifyingmath.com/"
tags = []
features = []
min_version = "0.20.7"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
